trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v2.1.0

jobs:
- template: job--pre-commit.yml@asottile
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py27, py36]
    os: macos
    wheel_tags: true
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py27]
    os: windows
    architectures: [x64, x86]
    name_postfix: _py27
    wheel_tags: true
    pre_test:
    - script: rm -rf libsass/test
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py36, py37, py38, py39]
    os: windows
    architectures: [x64, x86]
    wheel_tags: true
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy, pypy3, py27, py36, py37, py38, py39]
    os: linux
