name: main

on:
  push:
    branches: [main, test-me-*]
    tags: '*'
  pull_request:

jobs:
  main-windows:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.4.2
    with:
      env: '["py37"]'
      os: windows-latest
      arch: '["x64", "x86"]'
      wheel-tags: true
      submodules: true
  main-macos:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.4.2
    with:
      env: '["py37"]'
      os: macos-latest
      wheel-tags: true
      submodules: true
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.4.2
    with:
      env: '["pypy3", "py37", "py38", "py39", "py310"]'
      os: ubuntu-latest
      submodules: true
